name: Receiver outside trigger event

on: repository_dispatch

jobs:
  confirm_outside_event:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.tag }}'"
